[package]
name = "rust_virtual_kvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "common",
    "server",
    "client",
]

[dependencies]
bincode = "1.3.3"
chacha20poly1305 = "0.10.1"
x25519-dalek = { version = "2.0.1", features = ["serde"] }
common = { path = "common" }
evdev = { version = "0.12.2", features = ["serde", "tokio"] }
serde = { version = "1.0.214", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = "0.7.13"
uuid = { version = "1.15.0", features = ["v4"] }

[[bin]]
name = "client"
path = "client/src/main.rs"

[[bin]]
name = "server"
path = "server/src/main.rs"

