[package]
name = "rust_virtual_kvm"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
evdev = { version = "0.12.2", features = ["serde"] }
serde = { version = "1.0.214", features = ["derive"] }

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"
