use crate::{mapper::error::EventMappingError, KeyboardEventType};

impl From<crate::InputEvent> for evdev::InputEvent {
    fn from(value: crate::InputEvent) -> Self {
        match value {
            crate::InputEvent::Keyboard { key, event_type } => evdev::InputEvent::new(
                evdev::EventType::KEY,
                evdev::Key::from(key).code(),
                to_evdev_value(event_type),
            ),
            crate::InputEvent::Pointer { axis, diff } => match axis {
                crate::PointerAxis::Horizontal => evdev::InputEvent::new(
                    evdev::EventType::RELATIVE,
                    evdev::RelativeAxisType::REL_X.0,
                    diff,
                ),
                crate::PointerAxis::Vertical => evdev::InputEvent::new(
                    evdev::EventType::RELATIVE,
                    evdev::RelativeAxisType::REL_Y.0,
                    diff,
                ),
            },
        }
    }
}

impl TryFrom<evdev::InputEvent> for crate::InputEvent {
    type Error = EventMappingError;

    fn try_from(value: evdev::InputEvent) -> Result<Self, Self::Error> {
        match value.event_type() {
            evdev::EventType::KEY => Ok(crate::InputEvent::Keyboard {
                key: evdev::Key::new(value.code()).into(),
                event_type: match value.value() {
                    0 => KeyboardEventType::KeyReleased,
                    1 => KeyboardEventType::KeyPressed,
                    2 => KeyboardEventType::KeyHeld,
                    _ => {
                        eprintln!("Invalid key event type value: {value:?}");
                        return Err(EventMappingError::InvalidEventError);
                    }
                },
            }),
            evdev::EventType::RELATIVE => {
                let axis = if value.code() == evdev::RelativeAxisType::REL_X.0 {
                    crate::PointerAxis::Horizontal
                } else if value.code() == evdev::RelativeAxisType::REL_Y.0 {
                    crate::PointerAxis::Vertical
                } else {
                    eprintln!("Invalid relative event axis value: {value:?}");
                    return Err(EventMappingError::InvalidEventError);
                };
                Ok(crate::InputEvent::Pointer {
                    axis,
                    diff: value.value(),
                })
            }
            _ => {
                eprintln!("Unsupported event type: {value:?}");
                Err(EventMappingError::UnsupportedEventError)
            }
        }
    }
}

fn to_evdev_value(event_type: crate::KeyboardEventType) -> i32 {
    match event_type {
        KeyboardEventType::KeyPressed => 1,
        KeyboardEventType::KeyReleased => 0,
        KeyboardEventType::KeyHeld => 2,
    }
}

impl From<crate::Key> for evdev::Key {
    fn from(value: crate::Key) -> Self {
        match value {
            crate::Key::KEY_RESERVED => evdev::Key::KEY_RESERVED,
            crate::Key::KEY_ESC => evdev::Key::KEY_ESC,
            crate::Key::KEY_1 => evdev::Key::KEY_1,
            crate::Key::KEY_2 => evdev::Key::KEY_2,
            crate::Key::KEY_3 => evdev::Key::KEY_3,
            crate::Key::KEY_4 => evdev::Key::KEY_4,
            crate::Key::KEY_5 => evdev::Key::KEY_5,
            crate::Key::KEY_6 => evdev::Key::KEY_6,
            crate::Key::KEY_7 => evdev::Key::KEY_7,
            crate::Key::KEY_8 => evdev::Key::KEY_8,
            crate::Key::KEY_9 => evdev::Key::KEY_9,
            crate::Key::KEY_0 => evdev::Key::KEY_0,
            crate::Key::KEY_MINUS => evdev::Key::KEY_MINUS,
            crate::Key::KEY_EQUAL => evdev::Key::KEY_EQUAL,
            crate::Key::KEY_BACKSPACE => evdev::Key::KEY_BACKSPACE,
            crate::Key::KEY_TAB => evdev::Key::KEY_TAB,
            crate::Key::KEY_Q => evdev::Key::KEY_Q,
            crate::Key::KEY_W => evdev::Key::KEY_W,
            crate::Key::KEY_E => evdev::Key::KEY_E,
            crate::Key::KEY_R => evdev::Key::KEY_R,
            crate::Key::KEY_T => evdev::Key::KEY_T,
            crate::Key::KEY_Y => evdev::Key::KEY_Y,
            crate::Key::KEY_U => evdev::Key::KEY_U,
            crate::Key::KEY_I => evdev::Key::KEY_I,
            crate::Key::KEY_O => evdev::Key::KEY_O,
            crate::Key::KEY_P => evdev::Key::KEY_P,
            crate::Key::KEY_LEFTBRACE => evdev::Key::KEY_LEFTBRACE,
            crate::Key::KEY_RIGHTBRACE => evdev::Key::KEY_RIGHTBRACE,
            crate::Key::KEY_ENTER => evdev::Key::KEY_ENTER,
            crate::Key::KEY_LEFTCTRL => evdev::Key::KEY_LEFTCTRL,
            crate::Key::KEY_A => evdev::Key::KEY_A,
            crate::Key::KEY_S => evdev::Key::KEY_S,
            crate::Key::KEY_D => evdev::Key::KEY_D,
            crate::Key::KEY_F => evdev::Key::KEY_F,
            crate::Key::KEY_G => evdev::Key::KEY_G,
            crate::Key::KEY_H => evdev::Key::KEY_H,
            crate::Key::KEY_J => evdev::Key::KEY_J,
            crate::Key::KEY_K => evdev::Key::KEY_K,
            crate::Key::KEY_L => evdev::Key::KEY_L,
            crate::Key::KEY_SEMICOLON => evdev::Key::KEY_SEMICOLON,
            crate::Key::KEY_APOSTROPHE => evdev::Key::KEY_APOSTROPHE,
            crate::Key::KEY_GRAVE => evdev::Key::KEY_GRAVE,
            crate::Key::KEY_LEFTSHIFT => evdev::Key::KEY_LEFTSHIFT,
            crate::Key::KEY_BACKSLASH => evdev::Key::KEY_BACKSLASH,
            crate::Key::KEY_Z => evdev::Key::KEY_Z,
            crate::Key::KEY_X => evdev::Key::KEY_X,
            crate::Key::KEY_C => evdev::Key::KEY_C,
            crate::Key::KEY_V => evdev::Key::KEY_V,
            crate::Key::KEY_B => evdev::Key::KEY_B,
            crate::Key::KEY_N => evdev::Key::KEY_N,
            crate::Key::KEY_M => evdev::Key::KEY_M,
            crate::Key::KEY_COMMA => evdev::Key::KEY_COMMA,
            crate::Key::KEY_DOT => evdev::Key::KEY_DOT,
            crate::Key::KEY_SLASH => evdev::Key::KEY_SLASH,
            crate::Key::KEY_RIGHTSHIFT => evdev::Key::KEY_RIGHTSHIFT,
            crate::Key::KEY_KPASTERISK => evdev::Key::KEY_KPASTERISK,
            crate::Key::KEY_LEFTALT => evdev::Key::KEY_LEFTALT,
            crate::Key::KEY_SPACE => evdev::Key::KEY_SPACE,
            crate::Key::KEY_CAPSLOCK => evdev::Key::KEY_CAPSLOCK,
            crate::Key::KEY_F1 => evdev::Key::KEY_F1,
            crate::Key::KEY_F2 => evdev::Key::KEY_F2,
            crate::Key::KEY_F3 => evdev::Key::KEY_F3,
            crate::Key::KEY_F4 => evdev::Key::KEY_F4,
            crate::Key::KEY_F5 => evdev::Key::KEY_F5,
            crate::Key::KEY_F6 => evdev::Key::KEY_F6,
            crate::Key::KEY_F7 => evdev::Key::KEY_F7,
            crate::Key::KEY_F8 => evdev::Key::KEY_F8,
            crate::Key::KEY_F9 => evdev::Key::KEY_F9,
            crate::Key::KEY_F10 => evdev::Key::KEY_F10,
            crate::Key::KEY_NUMLOCK => evdev::Key::KEY_NUMLOCK,
            crate::Key::KEY_SCROLLLOCK => evdev::Key::KEY_SCROLLLOCK,
            crate::Key::KEY_KP7 => evdev::Key::KEY_KP7,
            crate::Key::KEY_KP8 => evdev::Key::KEY_KP8,
            crate::Key::KEY_KP9 => evdev::Key::KEY_KP9,
            crate::Key::KEY_KPMINUS => evdev::Key::KEY_KPMINUS,
            crate::Key::KEY_KP4 => evdev::Key::KEY_KP4,
            crate::Key::KEY_KP5 => evdev::Key::KEY_KP5,
            crate::Key::KEY_KP6 => evdev::Key::KEY_KP6,
            crate::Key::KEY_KPPLUS => evdev::Key::KEY_KPPLUS,
            crate::Key::KEY_KP1 => evdev::Key::KEY_KP1,
            crate::Key::KEY_KP2 => evdev::Key::KEY_KP2,
            crate::Key::KEY_KP3 => evdev::Key::KEY_KP3,
            crate::Key::KEY_KP0 => evdev::Key::KEY_KP0,
            crate::Key::KEY_KPDOT => evdev::Key::KEY_KPDOT,
            crate::Key::KEY_ZENKAKUHANKAKU => evdev::Key::KEY_ZENKAKUHANKAKU,
            crate::Key::KEY_102ND => evdev::Key::KEY_102ND,
            crate::Key::KEY_F11 => evdev::Key::KEY_F11,
            crate::Key::KEY_F12 => evdev::Key::KEY_F12,
            crate::Key::KEY_RO => evdev::Key::KEY_RO,
            crate::Key::KEY_KATAKANA => evdev::Key::KEY_KATAKANA,
            crate::Key::KEY_HIRAGANA => evdev::Key::KEY_HIRAGANA,
            crate::Key::KEY_HENKAN => evdev::Key::KEY_HENKAN,
            crate::Key::KEY_KATAKANAHIRAGANA => evdev::Key::KEY_KATAKANAHIRAGANA,
            crate::Key::KEY_MUHENKAN => evdev::Key::KEY_MUHENKAN,
            crate::Key::KEY_KPJPCOMMA => evdev::Key::KEY_KPJPCOMMA,
            crate::Key::KEY_KPENTER => evdev::Key::KEY_KPENTER,
            crate::Key::KEY_RIGHTCTRL => evdev::Key::KEY_RIGHTCTRL,
            crate::Key::KEY_KPSLASH => evdev::Key::KEY_KPSLASH,
            crate::Key::KEY_SYSRQ => evdev::Key::KEY_SYSRQ,
            crate::Key::KEY_RIGHTALT => evdev::Key::KEY_RIGHTALT,
            crate::Key::KEY_LINEFEED => evdev::Key::KEY_LINEFEED,
            crate::Key::KEY_HOME => evdev::Key::KEY_HOME,
            crate::Key::KEY_UP => evdev::Key::KEY_UP,
            crate::Key::KEY_PAGEUP => evdev::Key::KEY_PAGEUP,
            crate::Key::KEY_LEFT => evdev::Key::KEY_LEFT,
            crate::Key::KEY_RIGHT => evdev::Key::KEY_RIGHT,
            crate::Key::KEY_END => evdev::Key::KEY_END,
            crate::Key::KEY_DOWN => evdev::Key::KEY_DOWN,
            crate::Key::KEY_PAGEDOWN => evdev::Key::KEY_PAGEDOWN,
            crate::Key::KEY_INSERT => evdev::Key::KEY_INSERT,
            crate::Key::KEY_DELETE => evdev::Key::KEY_DELETE,
            crate::Key::KEY_MACRO => evdev::Key::KEY_MACRO,
            crate::Key::KEY_MUTE => evdev::Key::KEY_MUTE,
            crate::Key::KEY_VOLUMEDOWN => evdev::Key::KEY_VOLUMEDOWN,
            crate::Key::KEY_VOLUMEUP => evdev::Key::KEY_VOLUMEUP,
            crate::Key::KEY_POWER => evdev::Key::KEY_POWER,
            crate::Key::KEY_KPEQUAL => evdev::Key::KEY_KPEQUAL,
            crate::Key::KEY_KPPLUSMINUS => evdev::Key::KEY_KPPLUSMINUS,
            crate::Key::KEY_PAUSE => evdev::Key::KEY_PAUSE,
            crate::Key::KEY_SCALE => evdev::Key::KEY_SCALE,
            crate::Key::KEY_KPCOMMA => evdev::Key::KEY_KPCOMMA,
            crate::Key::KEY_HANGEUL => evdev::Key::KEY_HANGEUL,
            crate::Key::KEY_HANJA => evdev::Key::KEY_HANJA,
            crate::Key::KEY_YEN => evdev::Key::KEY_YEN,
            crate::Key::KEY_LEFTMETA => evdev::Key::KEY_LEFTMETA,
            crate::Key::KEY_RIGHTMETA => evdev::Key::KEY_RIGHTMETA,
            crate::Key::KEY_COMPOSE => evdev::Key::KEY_COMPOSE,
            crate::Key::KEY_STOP => evdev::Key::KEY_STOP,
            crate::Key::KEY_AGAIN => evdev::Key::KEY_AGAIN,
            crate::Key::KEY_PROPS => evdev::Key::KEY_PROPS,
            crate::Key::KEY_UNDO => evdev::Key::KEY_UNDO,
            crate::Key::KEY_FRONT => evdev::Key::KEY_FRONT,
            crate::Key::KEY_COPY => evdev::Key::KEY_COPY,
            crate::Key::KEY_OPEN => evdev::Key::KEY_OPEN,
            crate::Key::KEY_PASTE => evdev::Key::KEY_PASTE,
            crate::Key::KEY_FIND => evdev::Key::KEY_FIND,
            crate::Key::KEY_CUT => evdev::Key::KEY_CUT,
            crate::Key::KEY_HELP => evdev::Key::KEY_HELP,
            crate::Key::KEY_MENU => evdev::Key::KEY_MENU,
            crate::Key::KEY_CALC => evdev::Key::KEY_CALC,
            crate::Key::KEY_SETUP => evdev::Key::KEY_SETUP,
            crate::Key::KEY_SLEEP => evdev::Key::KEY_SLEEP,
            crate::Key::KEY_WAKEUP => evdev::Key::KEY_WAKEUP,
            crate::Key::KEY_FILE => evdev::Key::KEY_FILE,
            crate::Key::KEY_SENDFILE => evdev::Key::KEY_SENDFILE,
            crate::Key::KEY_DELETEFILE => evdev::Key::KEY_DELETEFILE,
            crate::Key::KEY_XFER => evdev::Key::KEY_XFER,
            crate::Key::KEY_PROG1 => evdev::Key::KEY_PROG1,
            crate::Key::KEY_PROG2 => evdev::Key::KEY_PROG2,
            crate::Key::KEY_WWW => evdev::Key::KEY_WWW,
            crate::Key::KEY_MSDOS => evdev::Key::KEY_MSDOS,
            crate::Key::KEY_COFFEE => evdev::Key::KEY_COFFEE,
            crate::Key::KEY_DIRECTION => evdev::Key::KEY_DIRECTION,
            crate::Key::KEY_CYCLEWINDOWS => evdev::Key::KEY_CYCLEWINDOWS,
            crate::Key::KEY_MAIL => evdev::Key::KEY_MAIL,
            crate::Key::KEY_BOOKMARKS => evdev::Key::KEY_BOOKMARKS,
            crate::Key::KEY_COMPUTER => evdev::Key::KEY_COMPUTER,
            crate::Key::KEY_BACK => evdev::Key::KEY_BACK,
            crate::Key::KEY_FORWARD => evdev::Key::KEY_FORWARD,
            crate::Key::KEY_CLOSECD => evdev::Key::KEY_CLOSECD,
            crate::Key::KEY_EJECTCD => evdev::Key::KEY_EJECTCD,
            crate::Key::KEY_EJECTCLOSECD => evdev::Key::KEY_EJECTCLOSECD,
            crate::Key::KEY_NEXTSONG => evdev::Key::KEY_NEXTSONG,
            crate::Key::KEY_PLAYPAUSE => evdev::Key::KEY_PLAYPAUSE,
            crate::Key::KEY_PREVIOUSSONG => evdev::Key::KEY_PREVIOUSSONG,
            crate::Key::KEY_STOPCD => evdev::Key::KEY_STOPCD,
            crate::Key::KEY_RECORD => evdev::Key::KEY_RECORD,
            crate::Key::KEY_REWIND => evdev::Key::KEY_REWIND,
            crate::Key::KEY_PHONE => evdev::Key::KEY_PHONE,
            crate::Key::KEY_ISO => evdev::Key::KEY_ISO,
            crate::Key::KEY_CONFIG => evdev::Key::KEY_CONFIG,
            crate::Key::KEY_HOMEPAGE => evdev::Key::KEY_HOMEPAGE,
            crate::Key::KEY_REFRESH => evdev::Key::KEY_REFRESH,
            crate::Key::KEY_EXIT => evdev::Key::KEY_EXIT,
            crate::Key::KEY_MOVE => evdev::Key::KEY_MOVE,
            crate::Key::KEY_EDIT => evdev::Key::KEY_EDIT,
            crate::Key::KEY_SCROLLUP => evdev::Key::KEY_SCROLLUP,
            crate::Key::KEY_SCROLLDOWN => evdev::Key::KEY_SCROLLDOWN,
            crate::Key::KEY_KPLEFTPAREN => evdev::Key::KEY_KPLEFTPAREN,
            crate::Key::KEY_KPRIGHTPAREN => evdev::Key::KEY_KPRIGHTPAREN,
            crate::Key::KEY_NEW => evdev::Key::KEY_NEW,
            crate::Key::KEY_REDO => evdev::Key::KEY_REDO,
            crate::Key::KEY_F13 => evdev::Key::KEY_F13,
            crate::Key::KEY_F14 => evdev::Key::KEY_F14,
            crate::Key::KEY_F15 => evdev::Key::KEY_F15,
            crate::Key::KEY_F16 => evdev::Key::KEY_F16,
            crate::Key::KEY_F17 => evdev::Key::KEY_F17,
            crate::Key::KEY_F18 => evdev::Key::KEY_F18,
            crate::Key::KEY_F19 => evdev::Key::KEY_F19,
            crate::Key::KEY_F20 => evdev::Key::KEY_F20,
            crate::Key::KEY_F21 => evdev::Key::KEY_F21,
            crate::Key::KEY_F22 => evdev::Key::KEY_F22,
            crate::Key::KEY_F23 => evdev::Key::KEY_F23,
            crate::Key::KEY_F24 => evdev::Key::KEY_F24,
            crate::Key::BTN_LEFT => evdev::Key::BTN_LEFT,
            crate::Key::BTN_RIGHT => evdev::Key::BTN_RIGHT,
            crate::Key::BTN_MIDDLE => evdev::Key::BTN_MIDDLE,
            crate::Key::BTN_SIDE => evdev::Key::BTN_SIDE,
            crate::Key::BTN_EXTRA => evdev::Key::BTN_EXTRA,
            crate::Key::BTN_FORWARD => evdev::Key::BTN_FORWARD,
            crate::Key::BTN_BACK => evdev::Key::BTN_BACK,
        }
    }
}

impl From<evdev::Key> for crate::Key {
    fn from(val: evdev::Key) -> Self {
        match val {
            evdev::Key::KEY_RESERVED => crate::Key::KEY_RESERVED,
            evdev::Key::KEY_ESC => crate::Key::KEY_ESC,
            evdev::Key::KEY_1 => crate::Key::KEY_1,
            evdev::Key::KEY_2 => crate::Key::KEY_2,
            evdev::Key::KEY_3 => crate::Key::KEY_3,
            evdev::Key::KEY_4 => crate::Key::KEY_4,
            evdev::Key::KEY_5 => crate::Key::KEY_5,
            evdev::Key::KEY_6 => crate::Key::KEY_6,
            evdev::Key::KEY_7 => crate::Key::KEY_7,
            evdev::Key::KEY_8 => crate::Key::KEY_8,
            evdev::Key::KEY_9 => crate::Key::KEY_9,
            evdev::Key::KEY_0 => crate::Key::KEY_0,
            evdev::Key::KEY_MINUS => crate::Key::KEY_MINUS,
            evdev::Key::KEY_EQUAL => crate::Key::KEY_EQUAL,
            evdev::Key::KEY_BACKSPACE => crate::Key::KEY_BACKSPACE,
            evdev::Key::KEY_TAB => crate::Key::KEY_TAB,
            evdev::Key::KEY_Q => crate::Key::KEY_Q,
            evdev::Key::KEY_W => crate::Key::KEY_W,
            evdev::Key::KEY_E => crate::Key::KEY_E,
            evdev::Key::KEY_R => crate::Key::KEY_R,
            evdev::Key::KEY_T => crate::Key::KEY_T,
            evdev::Key::KEY_Y => crate::Key::KEY_Y,
            evdev::Key::KEY_U => crate::Key::KEY_U,
            evdev::Key::KEY_I => crate::Key::KEY_I,
            evdev::Key::KEY_O => crate::Key::KEY_O,
            evdev::Key::KEY_P => crate::Key::KEY_P,
            evdev::Key::KEY_LEFTBRACE => crate::Key::KEY_LEFTBRACE,
            evdev::Key::KEY_RIGHTBRACE => crate::Key::KEY_RIGHTBRACE,
            evdev::Key::KEY_ENTER => crate::Key::KEY_ENTER,
            evdev::Key::KEY_LEFTCTRL => crate::Key::KEY_LEFTCTRL,
            evdev::Key::KEY_A => crate::Key::KEY_A,
            evdev::Key::KEY_S => crate::Key::KEY_S,
            evdev::Key::KEY_D => crate::Key::KEY_D,
            evdev::Key::KEY_F => crate::Key::KEY_F,
            evdev::Key::KEY_G => crate::Key::KEY_G,
            evdev::Key::KEY_H => crate::Key::KEY_H,
            evdev::Key::KEY_J => crate::Key::KEY_J,
            evdev::Key::KEY_K => crate::Key::KEY_K,
            evdev::Key::KEY_L => crate::Key::KEY_L,
            evdev::Key::KEY_SEMICOLON => crate::Key::KEY_SEMICOLON,
            evdev::Key::KEY_APOSTROPHE => crate::Key::KEY_APOSTROPHE,
            evdev::Key::KEY_GRAVE => crate::Key::KEY_GRAVE,
            evdev::Key::KEY_LEFTSHIFT => crate::Key::KEY_LEFTSHIFT,
            evdev::Key::KEY_BACKSLASH => crate::Key::KEY_BACKSLASH,
            evdev::Key::KEY_Z => crate::Key::KEY_Z,
            evdev::Key::KEY_X => crate::Key::KEY_X,
            evdev::Key::KEY_C => crate::Key::KEY_C,
            evdev::Key::KEY_V => crate::Key::KEY_V,
            evdev::Key::KEY_B => crate::Key::KEY_B,
            evdev::Key::KEY_N => crate::Key::KEY_N,
            evdev::Key::KEY_M => crate::Key::KEY_M,
            evdev::Key::KEY_COMMA => crate::Key::KEY_COMMA,
            evdev::Key::KEY_DOT => crate::Key::KEY_DOT,
            evdev::Key::KEY_SLASH => crate::Key::KEY_SLASH,
            evdev::Key::KEY_RIGHTSHIFT => crate::Key::KEY_RIGHTSHIFT,
            evdev::Key::KEY_KPASTERISK => crate::Key::KEY_KPASTERISK,
            evdev::Key::KEY_LEFTALT => crate::Key::KEY_LEFTALT,
            evdev::Key::KEY_SPACE => crate::Key::KEY_SPACE,
            evdev::Key::KEY_CAPSLOCK => crate::Key::KEY_CAPSLOCK,
            evdev::Key::KEY_F1 => crate::Key::KEY_F1,
            evdev::Key::KEY_F2 => crate::Key::KEY_F2,
            evdev::Key::KEY_F3 => crate::Key::KEY_F3,
            evdev::Key::KEY_F4 => crate::Key::KEY_F4,
            evdev::Key::KEY_F5 => crate::Key::KEY_F5,
            evdev::Key::KEY_F6 => crate::Key::KEY_F6,
            evdev::Key::KEY_F7 => crate::Key::KEY_F7,
            evdev::Key::KEY_F8 => crate::Key::KEY_F8,
            evdev::Key::KEY_F9 => crate::Key::KEY_F9,
            evdev::Key::KEY_F10 => crate::Key::KEY_F10,
            evdev::Key::KEY_NUMLOCK => crate::Key::KEY_NUMLOCK,
            evdev::Key::KEY_SCROLLLOCK => crate::Key::KEY_SCROLLLOCK,
            evdev::Key::KEY_KP7 => crate::Key::KEY_KP7,
            evdev::Key::KEY_KP8 => crate::Key::KEY_KP8,
            evdev::Key::KEY_KP9 => crate::Key::KEY_KP9,
            evdev::Key::KEY_KPMINUS => crate::Key::KEY_KPMINUS,
            evdev::Key::KEY_KP4 => crate::Key::KEY_KP4,
            evdev::Key::KEY_KP5 => crate::Key::KEY_KP5,
            evdev::Key::KEY_KP6 => crate::Key::KEY_KP6,
            evdev::Key::KEY_KPPLUS => crate::Key::KEY_KPPLUS,
            evdev::Key::KEY_KP1 => crate::Key::KEY_KP1,
            evdev::Key::KEY_KP2 => crate::Key::KEY_KP2,
            evdev::Key::KEY_KP3 => crate::Key::KEY_KP3,
            evdev::Key::KEY_KP0 => crate::Key::KEY_KP0,
            evdev::Key::KEY_KPDOT => crate::Key::KEY_KPDOT,
            evdev::Key::KEY_ZENKAKUHANKAKU => crate::Key::KEY_ZENKAKUHANKAKU,
            evdev::Key::KEY_102ND => crate::Key::KEY_102ND,
            evdev::Key::KEY_F11 => crate::Key::KEY_F11,
            evdev::Key::KEY_F12 => crate::Key::KEY_F12,
            evdev::Key::KEY_RO => crate::Key::KEY_RO,
            evdev::Key::KEY_KATAKANA => crate::Key::KEY_KATAKANA,
            evdev::Key::KEY_HIRAGANA => crate::Key::KEY_HIRAGANA,
            evdev::Key::KEY_HENKAN => crate::Key::KEY_HENKAN,
            evdev::Key::KEY_KATAKANAHIRAGANA => crate::Key::KEY_KATAKANAHIRAGANA,
            evdev::Key::KEY_MUHENKAN => crate::Key::KEY_MUHENKAN,
            evdev::Key::KEY_KPJPCOMMA => crate::Key::KEY_KPJPCOMMA,
            evdev::Key::KEY_KPENTER => crate::Key::KEY_KPENTER,
            evdev::Key::KEY_RIGHTCTRL => crate::Key::KEY_RIGHTCTRL,
            evdev::Key::KEY_KPSLASH => crate::Key::KEY_KPSLASH,
            evdev::Key::KEY_SYSRQ => crate::Key::KEY_SYSRQ,
            evdev::Key::KEY_RIGHTALT => crate::Key::KEY_RIGHTALT,
            evdev::Key::KEY_LINEFEED => crate::Key::KEY_LINEFEED,
            evdev::Key::KEY_HOME => crate::Key::KEY_HOME,
            evdev::Key::KEY_UP => crate::Key::KEY_UP,
            evdev::Key::KEY_PAGEUP => crate::Key::KEY_PAGEUP,
            evdev::Key::KEY_LEFT => crate::Key::KEY_LEFT,
            evdev::Key::KEY_RIGHT => crate::Key::KEY_RIGHT,
            evdev::Key::KEY_END => crate::Key::KEY_END,
            evdev::Key::KEY_DOWN => crate::Key::KEY_DOWN,
            evdev::Key::KEY_PAGEDOWN => crate::Key::KEY_PAGEDOWN,
            evdev::Key::KEY_INSERT => crate::Key::KEY_INSERT,
            evdev::Key::KEY_DELETE => crate::Key::KEY_DELETE,
            evdev::Key::KEY_MACRO => crate::Key::KEY_MACRO,
            evdev::Key::KEY_MUTE => crate::Key::KEY_MUTE,
            evdev::Key::KEY_VOLUMEDOWN => crate::Key::KEY_VOLUMEDOWN,
            evdev::Key::KEY_VOLUMEUP => crate::Key::KEY_VOLUMEUP,
            evdev::Key::KEY_POWER => crate::Key::KEY_POWER,
            evdev::Key::KEY_KPEQUAL => crate::Key::KEY_KPEQUAL,
            evdev::Key::KEY_KPPLUSMINUS => crate::Key::KEY_KPPLUSMINUS,
            evdev::Key::KEY_PAUSE => crate::Key::KEY_PAUSE,
            evdev::Key::KEY_SCALE => crate::Key::KEY_SCALE,
            evdev::Key::KEY_KPCOMMA => crate::Key::KEY_KPCOMMA,
            evdev::Key::KEY_HANGEUL => crate::Key::KEY_HANGEUL,
            evdev::Key::KEY_HANJA => crate::Key::KEY_HANJA,
            evdev::Key::KEY_YEN => crate::Key::KEY_YEN,
            evdev::Key::KEY_LEFTMETA => crate::Key::KEY_LEFTMETA,
            evdev::Key::KEY_RIGHTMETA => crate::Key::KEY_RIGHTMETA,
            evdev::Key::KEY_COMPOSE => crate::Key::KEY_COMPOSE,
            evdev::Key::KEY_STOP => crate::Key::KEY_STOP,
            evdev::Key::KEY_AGAIN => crate::Key::KEY_AGAIN,
            evdev::Key::KEY_PROPS => crate::Key::KEY_PROPS,
            evdev::Key::KEY_UNDO => crate::Key::KEY_UNDO,
            evdev::Key::KEY_FRONT => crate::Key::KEY_FRONT,
            evdev::Key::KEY_COPY => crate::Key::KEY_COPY,
            evdev::Key::KEY_OPEN => crate::Key::KEY_OPEN,
            evdev::Key::KEY_PASTE => crate::Key::KEY_PASTE,
            evdev::Key::KEY_FIND => crate::Key::KEY_FIND,
            evdev::Key::KEY_CUT => crate::Key::KEY_CUT,
            evdev::Key::KEY_HELP => crate::Key::KEY_HELP,
            evdev::Key::KEY_MENU => crate::Key::KEY_MENU,
            evdev::Key::KEY_CALC => crate::Key::KEY_CALC,
            evdev::Key::KEY_SETUP => crate::Key::KEY_SETUP,
            evdev::Key::KEY_SLEEP => crate::Key::KEY_SLEEP,
            evdev::Key::KEY_WAKEUP => crate::Key::KEY_WAKEUP,
            evdev::Key::KEY_FILE => crate::Key::KEY_FILE,
            evdev::Key::KEY_SENDFILE => crate::Key::KEY_SENDFILE,
            evdev::Key::KEY_DELETEFILE => crate::Key::KEY_DELETEFILE,
            evdev::Key::KEY_XFER => crate::Key::KEY_XFER,
            evdev::Key::KEY_PROG1 => crate::Key::KEY_PROG1,
            evdev::Key::KEY_PROG2 => crate::Key::KEY_PROG2,
            evdev::Key::KEY_WWW => crate::Key::KEY_WWW,
            evdev::Key::KEY_MSDOS => crate::Key::KEY_MSDOS,
            evdev::Key::KEY_COFFEE => crate::Key::KEY_COFFEE,
            evdev::Key::KEY_DIRECTION => crate::Key::KEY_DIRECTION,
            evdev::Key::KEY_CYCLEWINDOWS => crate::Key::KEY_CYCLEWINDOWS,
            evdev::Key::KEY_MAIL => crate::Key::KEY_MAIL,
            evdev::Key::KEY_BOOKMARKS => crate::Key::KEY_BOOKMARKS,
            evdev::Key::KEY_COMPUTER => crate::Key::KEY_COMPUTER,
            evdev::Key::KEY_BACK => crate::Key::KEY_BACK,
            evdev::Key::KEY_FORWARD => crate::Key::KEY_FORWARD,
            evdev::Key::KEY_CLOSECD => crate::Key::KEY_CLOSECD,
            evdev::Key::KEY_EJECTCD => crate::Key::KEY_EJECTCD,
            evdev::Key::KEY_EJECTCLOSECD => crate::Key::KEY_EJECTCLOSECD,
            evdev::Key::KEY_NEXTSONG => crate::Key::KEY_NEXTSONG,
            evdev::Key::KEY_PLAYPAUSE => crate::Key::KEY_PLAYPAUSE,
            evdev::Key::KEY_PREVIOUSSONG => crate::Key::KEY_PREVIOUSSONG,
            evdev::Key::KEY_STOPCD => crate::Key::KEY_STOPCD,
            evdev::Key::KEY_RECORD => crate::Key::KEY_RECORD,
            evdev::Key::KEY_REWIND => crate::Key::KEY_REWIND,
            evdev::Key::KEY_PHONE => crate::Key::KEY_PHONE,
            evdev::Key::KEY_ISO => crate::Key::KEY_ISO,
            evdev::Key::KEY_CONFIG => crate::Key::KEY_CONFIG,
            evdev::Key::KEY_HOMEPAGE => crate::Key::KEY_HOMEPAGE,
            evdev::Key::KEY_REFRESH => crate::Key::KEY_REFRESH,
            evdev::Key::KEY_EXIT => crate::Key::KEY_EXIT,
            evdev::Key::KEY_MOVE => crate::Key::KEY_MOVE,
            evdev::Key::KEY_EDIT => crate::Key::KEY_EDIT,
            evdev::Key::KEY_SCROLLUP => crate::Key::KEY_SCROLLUP,
            evdev::Key::KEY_SCROLLDOWN => crate::Key::KEY_SCROLLDOWN,
            evdev::Key::KEY_KPLEFTPAREN => crate::Key::KEY_KPLEFTPAREN,
            evdev::Key::KEY_KPRIGHTPAREN => crate::Key::KEY_KPRIGHTPAREN,
            evdev::Key::KEY_NEW => crate::Key::KEY_NEW,
            evdev::Key::KEY_REDO => crate::Key::KEY_REDO,
            evdev::Key::KEY_F13 => crate::Key::KEY_F13,
            evdev::Key::KEY_F14 => crate::Key::KEY_F14,
            evdev::Key::KEY_F15 => crate::Key::KEY_F15,
            evdev::Key::KEY_F16 => crate::Key::KEY_F16,
            evdev::Key::KEY_F17 => crate::Key::KEY_F17,
            evdev::Key::KEY_F18 => crate::Key::KEY_F18,
            evdev::Key::KEY_F19 => crate::Key::KEY_F19,
            evdev::Key::KEY_F20 => crate::Key::KEY_F20,
            evdev::Key::KEY_F21 => crate::Key::KEY_F21,
            evdev::Key::KEY_F22 => crate::Key::KEY_F22,
            evdev::Key::KEY_F23 => crate::Key::KEY_F23,
            evdev::Key::KEY_F24 => crate::Key::KEY_F24,
            evdev::Key::BTN_LEFT => crate::Key::BTN_LEFT,
            evdev::Key::BTN_RIGHT => crate::Key::BTN_RIGHT,
            evdev::Key::BTN_MIDDLE => crate::Key::BTN_MIDDLE,
            evdev::Key::BTN_SIDE => crate::Key::BTN_SIDE,
            evdev::Key::BTN_EXTRA => crate::Key::BTN_EXTRA,
            evdev::Key::BTN_FORWARD => crate::Key::BTN_FORWARD,
            evdev::Key::BTN_BACK => crate::Key::BTN_BACK,
            _ => unimplemented!("Unsupported key {val:?}"),
        }
    }
}
